services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todoapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./ToDoApi
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: ./todo-frontend
    volumes:
    - ./todo-frontend:/app
    - /app/node_modules
    depends_on:
      - api
    ports:
      - "8080:5173"
    command: npm run dev -- --host

  migrations:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    volumes:
      - ./ToDoApi:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: